### ISSUE TITLE
Fehlermeldungen beim Starten des Adapters

### ISSUE THREAD

**Issue by Matten-Matten** [vader722/ioBroker.vuplus#11]
Wenn ich den Adapter starte (mit Webinterface Plugin auf meiner VU Solo SE V2), kommt folgende Fehlermeldung:
> `

vuplus.0 | 2018-02-07 13:21:20.865 | error |  
-- | -- | -- | --
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error | x
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error | Vuplus DVB-C NIM(SSH108) (DVB-C)
vuplus.0 | 2018-02-07 13:21:20.865 | error | Tuner A
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error | 192.168.0.1
vuplus.0 | 2018-02-07 13:21:20.865 | error | 255.255.255.0
vuplus.0 | 2018-02-07 13:21:20.865 | error | 192.168.0.60
vuplus.0 | 2018-02-07 13:21:20.865 | error | True
vuplus.0 | 2018-02-07 13:21:20.865 | error | 00:13:1b:f1:G4:5c
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error | solose
vuplus.0 | 2018-02-07 13:21:20.865 | error | 0
vuplus.0 | 2018-02-07 13:21:20.865 | error | 1.7.5
vuplus.0 | 2018-02-07 13:21:20.865 | error | Release 13.0.2 (BUILD: 2017-12-20)
vuplus.0 | 2018-02-07 13:21:20.865 | error | 2018-01-29-vti-master (e729409cb)
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error | Error for 'GETINFO': Cannot parse:

`
Und wenn ich den Adapter starte (mit Open Webif Plugin auf meiner VU Solo SE V2), kommt folgende Fehlermeldung:

> `

vuplus.0 | 2018-02-07 13:33:18.146 | error |  
-- | -- | -- | --
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | N/A
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0x0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error | Vuplus DVB-C NIM(SSH108) (DVB-C)
vuplus.0 | 2018-02-07 13:33:18.146 | error | Tuner A
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:21:20.865 | error | 192.168.0.1
vuplus.0 | 2018-02-07 13:21:20.865 | error | 255.255.255.0
vuplus.0 | 2018-02-07 13:21:20.865 | error | 192.168.0.60
vuplus.0 | 2018-02-07 13:21:20.865 | error | True
vuplus.0 | 2018-02-07 13:21:20.865 | error | 00:13:1b:f1:G4:5c
vuplus.0 | 2018-02-07 13:33:18.146 | error | Solo SE
vuplus.0 | 2018-02-07 13:33:18.146 | error | 0
vuplus.0 | 2018-02-07 13:33:18.146 | error | OWIF 1.2.8
vuplus.0 | 2018-02-07 13:33:18.146 | error | 3.13.5-20171204.r0
vuplus.0 | 2018-02-07 13:33:18.146 | error | 13.0.2
vuplus.0 | 2018-02-07 13:33:18.146 | error | VTi
vuplus.0 | 2018-02-07 13:33:18.146 | error | 2018-01-29-vti-master (e729409cb)
vuplus.0 | 2018-02-07 13:33:18.146 | error | openvuplus 3.0
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error |  
vuplus.0 | 2018-02-07 13:33:18.146 | error | Error for 'GETINFO': Cannot parse:
vuplus.0 | 2018-02-07 13:33:18.049 | error | No e2state found

`

**Comment by dYna77** [comment]
Same issue.
